name: C/C++ CI

on:
  push:
    branches: [ "test-at" ]
  pull_request:

jobs:
  build-android:

    timeout-minutes: 5
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        config:
          - {api_level: 23, ndk_version: 24.0.8215888, abi: arm64-v8a}

    steps:
    - name: Install dependencies
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install -y git build-essential cmake unzip openjdk-17-jdk
        sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
        ANDROID_TOOLS_PATH=${HOME}/sdk-sources/android-tools.zip
        mkdir -p ${HOME}/sdk-sources
        ANDROID_TOOLS_URL=https://googledownloads.cn/android/repository/commandlinetools-linux-11076708_latest.zip
        curl --location --fail "${ANDROID_TOOLS_URL}" -o "$ANDROID_TOOLS_PATH"
        ANDROID_HOME="${HOME}/SDKs/android"
        mkdir -p "$ANDROID_HOME"
        unzip -o "$ANDROID_TOOLS_PATH" -d "$ANDROID_HOME"
        ANDROID_BUILD_TOOLS_VERSION=28.0.3
        ANDROID_API_LEVEL=${{ matrix.config.api_level }}
        ANDROID_NDK_VERSION=${{ matrix.config.ndk_version }}
        JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        yes | "${ANDROID_HOME}"/cmdline-tools/bin/sdkmanager --sdk_root="${ANDROID_HOME}" --install "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" "platform-tools" "platforms;android-${ANDROID_API_LEVEL}" "ndk;${ANDROID_NDK_VERSION}"
        ls -l "${ANDROID_HOME}"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build RandomX
      run: |
        mkdir build
        cd build
        ANDROID_API_LEVEL=${{ matrix.config.api_level }}
        ANDROID_NDK_VERSION=${{ matrix.config.ndk_version }}
        ANDROID_NDK_HOME="${HOME}/SDKs/android/ndk/${ANDROID_NDK_VERSION}"
        ANDROID_ABI=${{ matrix.config.abi }}
        ANDROID_PLATFORM=android-${ANDROID_API_LEVEL}
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake  -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-23 ..
        make -j$(nproc)

    # - name: Run tests
    #   run: |
    #     build/randomx-tests

    # - name: Compress artifacts
    #   run: |
    #     tar -czvf ubuntu-${{ matrix.config.os }}.tar.gz -C ./build librandomx.a randomx-benchmark


    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ubuntu-${{ matrix.config.os }}
    #     path: ./ubuntu-${{ matrix.config.os }}.tar.gz