name: C/C++ CI

on:
  push:
    # tags: [ "v*.*.*" ]
    branches: ["macos"]
  pull_request:

jobs:
  

  build-macos:

    timeout-minutes: 5
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-14]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive


    - name: Build RandomX
      run: |
        arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        arch -x86_64 which brew
        arch -x86_64 /usr/local/bin/brew install llvm cmake
        export PATH="/usr/local/opt/llvm/bin:$PATH"
        export LDFLAGS="-L/usr/local/opt/llvm/lib -L/usr/local/opt/llvm/lib/c++ -Wl,-rpath,/usr/local/opt/llvm/lib/c++"
        export CPPFLAGS="-I/usr/local/opt/llvm/include"
        sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
        mkdir build
        cd build
        cmake .. \
        -DCMAKE_SYSTEM_NAME=Darwin \
        -DCMAKE_SYSTEM_PROCESSOR=x86_64 \
        -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang \
        -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ \
        -DCMAKE_OSX_ARCHITECTURES=x86_64 \
        -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
        -DCMAKE_C_FLAGS="-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" \
        -DCMAKE_CXX_FLAGS="-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" \
        -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/opt/llvm/lib/c++ -Wl,-rpath,/usr/local/opt/llvm/lib/c++"
        make VERBOSE=1
      
    - name: Display build log
      if: failure()
      run: cat build/CMakeFiles/CMakeError.log

    - name: Run tests
      run: |
        lipo -info build/randomx-tests

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: macos-artifact
    #     path: |
    #       ./build/librandomx.a
    #       ./build/randomx-benchmark

    - name: Compress artifacts
      run: |
        mkdir include lib
        cp -r src/*.h include
        cp build/librandomx.a lib
        tar -czvf macos-${{ matrix.os }}.tar.gz lib include build/randomx-benchmark

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.os }}
        path: ./macos-${{ matrix.os }}.tar.gz
