name: Macos

on:
  push:
    branches: ["macos"]
  pull_request:

jobs:
  build-macos:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        brew install llvm cmake

    - name: Set up environment
      run: |
        echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> $GITHUB_ENV
        echo 'export LDFLAGS="-L/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/llvm/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++"' >> $GITHUB_ENV
        echo 'export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"' >> $GITHUB_ENV

    - name: Build RandomX
      run: |
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_SYSTEM_NAME=Darwin \
          -DCMAKE_SYSTEM_PROCESSOR=x86_64 \
          -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang \
          -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ \
          -DCMAKE_OSX_ARCHITECTURES=x86_64 \
          -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk \
          -DCMAKE_C_FLAGS="-target x86_64-apple-macos10.15" \
          -DCMAKE_CXX_FLAGS="-target x86_64-apple-macos10.15" \
          -DCMAKE_EXE_LINKER_FLAGS="-target x86_64-apple-macos10.15"
        make VERBOSE=1

    - name: Display build log
      if: failure()
      run: cat build/CMakeFiles/CMakeError.log

    - name: Run tests
      run: |
        lipo -info build/randomx-tests

    - name: Compress artifacts
      run: |
        mkdir include lib
        cp -r src/*.h include
        cp build/librandomx.a lib
        tar -czvf macos-${{ matrix.os }}.tar.gz lib include build/randomx-benchmark

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.os }}
        path: ./macos-${{ matrix.os }}.tar.gz