name: C/C++ CI

on:
  push:
    # tags: [ "v*.*.*" ]
    branches: ["macos"]
  pull_request:

jobs:
  

  build-macos:

    timeout-minutes: 5
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-14]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive


    - name: Build RandomX
      run: |
        arch -x86_64 /usr/bin/env bash
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        HOMEBREW_NO_AUTO_UPDATE=1 brew install cmake llvm
        source ~/.bash_profile
        export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
        export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"
        export CC="/opt/homebrew/opt/llvm/bin/clang"
        export CXX="/opt/homebrew/opt/llvm/bin/clang++"
        mkdir build
        cmake -Bbuild -H. \
            -DCMAKE_C_COMPILER=$CC \
            -DCMAKE_CXX_COMPILER=$CXX \
            -DCMAKE_C_FLAGS="-target x86_64-apple-darwin $CPPFLAGS $LDFLAGS" \
            -DCMAKE_CXX_FLAGS="-target x86_64-apple-darwin $CPPFLAGS $LDFLAGS" \
            -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS"
        cmake --build build --config Release

    - name: Run tests
      run: |
        lipo -info build/randomx-tests

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: macos-artifact
    #     path: |
    #       ./build/librandomx.a
    #       ./build/randomx-benchmark

    - name: Compress artifacts
      run: |
        mkdir include lib
        cp -r src/*.h include
        cp build/librandomx.a lib
        tar -czvf macos-${{ matrix.os }}.tar.gz lib include build/randomx-benchmark

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.os }}
        path: ./macos-${{ matrix.os }}.tar.gz
